// The reference clips: for every movement that was authored against a
// video of the real lift (docs/animation-from-clip.md), which video, seen
// from where, and which library exercise it actually shows.
//
// This is the record of what each animation was corrected against. It is
// kept per POSE (the thing that was measured and re-authored); which
// exercises use a pose is App.tsx's POSE_FOR_EXERCISE, and
// `npm run check:references` joins the two into docs/reference-clips.md --
// one line per library exercise -- and fails on an entry that names a pose
// or an exercise that does not exist. Add an entry with every movement PR.

import type { PoseName } from "./poseData";

// Where the camera stood. Sagittal numbers (trunk, knee, hip) are only
// trustworthy from a side view; a three-quarter view gives them as
// projections (+-5 degrees); a front view gives the frontal plane; the head
// or foot end of a bench gives tempo and grip width and little else.
// "back" earns its place with the standing calf raise: a clip filmed from
// behind gives tempo and vertical travel and NO sagittal angle at all, and
// the record should say so rather than call it a side view.
export type ReferenceView = "side" | "three-quarter" | "front" | "back" | "head-end" | "foot-end";

export type ReferenceClip = {
  // YouTube video id; the URL is https://www.youtube.com/watch?v=<id>.
  videoId: string;
  title: string;
  channel: string;
  view: ReferenceView;
  // What was measured: reps and seconds, or the length of a hold.
  span: string;
  // The pull requests that authored (and corrected) the pose from this clip.
  prs: number[];
  // Date of the (last) merge, ISO.
  date: string;
  // The library exercises this clip actually shows. Every other exercise
  // mapped to the pose borrows it, and the generated doc says so.
  exercises: string[];
  notes?: string;
};

export const REFERENCE_CLIPS: Partial<Record<PoseName, ReferenceClip>> = {
  // --- Batch 1: the three big lifts ------------------------------------
  squat: {
    videoId: "-bJIpOq-LWk",
    title: "How to do a Barbell Back Squat",
    channel: "National Academy of Sports Medicine (NASM)",
    view: "three-quarter",
    span: "three reps in 11.8 s",
    prs: [254],
    date: "2026-09-08",
    exercises: ["Barbell Back Squat"],
    notes: "Stance and toe angle read face on; depth to parallel; SQUAT_FRAMES are shared by the goblet and bodyweight squats.",
  },
  trapBarDeadlift: {
    videoId: "ZJPZQklCSLs",
    title: "How To Hex Bar Deadlift Correctly",
    channel: "Motiv8 Fitness",
    view: "side",
    span: "two reps in 4.6 s",
    prs: [255, 256],
    date: "2026-09-08",
    exercises: ["Trap Bar Deadlift"],
  },
  bench: {
    videoId: "ejI1Nlsul9k",
    title: "Barbell Bench Press - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "foot-end",
    span: "three reps in 5.5 s",
    prs: [257, 258],
    date: "2026-09-08",
    exercises: ["Barbell Bench Press"],
    notes: "Foot-end camera: bar path, tempo and grip width; the chest-touch depth came from the skinned chest surface.",
  },

  // --- Batch 2: hinges and squats ---------------------------------------
  romanianDeadlift: {
    videoId: "ionx2qnNVMo",
    title: "BB RDL (Romanian Deadlift) Side View",
    channel: "Coach Savela",
    view: "side",
    span: "three reps in 9.8 s",
    prs: [260],
    date: "2026-09-09",
    exercises: ["Romanian Deadlift"],
  },
  stiffLegDeadlift: {
    videoId: "u3krqJlu7uc",
    title: "BB Stiff Legged Deadlift",
    channel: "Theory of Motion Exercise Library",
    view: "side",
    span: "five reps in 14.5 s",
    prs: [261],
    date: "2026-09-09",
    exercises: ["Stiff-Leg Deadlift"],
  },
  goodMorning: {
    videoId: "dEJ0FTm-CEk",
    title: "High Bar Good Morning",
    channel: "Renaissance Periodization",
    view: "side",
    span: "three reps in 17.3 s",
    prs: [262],
    date: "2026-09-09",
    exercises: ["Good Morning"],
  },
  kettlebellSwing: {
    videoId: "OPcG_thX6Dc",
    title: "The Russian Kettlebell Swing",
    channel: "Onnit",
    view: "side",
    span: "nine swings in 14.3 s",
    prs: [263],
    date: "2026-09-09",
    exercises: ["Kettlebell Swing"],
  },
  hipThrust: {
    videoId: "TSz4XEoFSFw",
    title: "Barbell Hip Thrust",
    channel: "My PT Hub",
    view: "side",
    span: "shoulders on a bench, three reps",
    prs: [264],
    date: "2026-09-09",
    exercises: ["Barbell Hip Thrust"],
    notes: "The OPEX clip in the batch list was a floor thrust with no bench, so this one was used instead.",
  },
  sumoDeadlift: {
    videoId: "OKMDYjnK8m8",
    title: "Sumo Deadlift - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "three-quarter",
    span: "four reps in 16 s",
    prs: [265],
    date: "2026-09-09",
    exercises: ["Sumo Deadlift"],
    notes: "The plates hide the knees at the bottom; knee angles were read off the overlays.",
  },
  frontSquat: {
    videoId: "Q1Ypb8ZNzI4",
    title: "How To Do A Barbell front squat",
    channel: "PureGym",
    view: "side",
    span: "the first 8 s, two reps before the cut to a close-up",
    prs: [266],
    date: "2026-09-09",
    exercises: ["Barbell Front Squat"],
  },
  splitSquat: {
    videoId: "Fmjj7wFJWRE",
    title: "Bulgarian Split Squat with Dumbbells",
    channel: "The Active Life",
    view: "side",
    span: "two reps after a 14 s setup",
    prs: [267],
    date: "2026-09-09",
    exercises: ["Bulgarian Split Squat", "Dumbbell Bulgarian Split Squat"],
    notes: "Step-Up and Dumbbell Step-Up still borrow this pose; a step-up's box is in FRONT of the lifter.",
  },
  splitSquatStatic: {
    videoId: "Py2Qeg-D5T0",
    title: "Split Squat - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "three reps in 11 s",
    prs: [268],
    date: "2026-09-09",
    exercises: ["Split Squat"],
  },
  walkingLunge: {
    videoId: "6wZoPedlpok",
    title: "Walking Lunge - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "two steps in 6.4 s",
    prs: [269],
    date: "2026-09-09",
    exercises: ["Walking Lunge"],
  },
  legPress: {
    videoId: "B8KqmwdomoU",
    title: "Leg Press Machine Press - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reps in 12 s",
    prs: [270],
    date: "2026-09-09",
    exercises: ["Leg Press"],
    notes: "The program builder never puts the leg press in a session; the pose is reachable only through the library.",
  },
  boxSquat: {
    videoId: "rMEPHwNhQfo",
    title: "Box Squat Movement Demo",
    channel: "The Active Life",
    view: "side",
    span: "three reps after a 7 s walk-out",
    prs: [271],
    date: "2026-09-09",
    exercises: ["Box Squat"],
  },

  // --- Batch 3: push and pull -------------------------------------------
  overheadPress: {
    videoId: "0YYeELi896g",
    title: "How to Overhead Press Correctly (Military Press)",
    channel: "TylerPath",
    view: "three-quarter",
    span: "three reps between the cuts",
    prs: [272],
    date: "2026-09-09",
    exercises: ["Barbell Overhead Press"],
  },
  bentRow: {
    videoId: "bm0_q9bR_HA",
    title: "How to do a Barbell Bent Over Row Pronated",
    channel: "National Academy of Sports Medicine (NASM)",
    view: "side",
    span: "three reps after a 6 s hinge down",
    prs: [273],
    date: "2026-09-09",
    exercises: ["Barbell Row"],
  },
  pullUp: {
    videoId: "jgFel4wZl3I",
    title: "Strict Pull Up - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reps in 8.6 s",
    prs: [274],
    date: "2026-09-09",
    exercises: ["Pull-Up"],
  },
  pulldown: {
    videoId: "PEv0gTcMY3g",
    title: "Cable Lat Pulldown Machine - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "three-quarter",
    span: "four reps in 10.5 s",
    prs: [275],
    date: "2026-09-09",
    exercises: ["Lat Pulldown"],
  },
  seatedRow: {
    videoId: "4ZbqM_gcgAI",
    title: "Seated Cable Row - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "three reps in 9.5 s",
    prs: [276],
    date: "2026-09-09",
    exercises: ["Seated Cable Row"],
  },
  pushUp: {
    videoId: "Ql8PKKsDE70",
    title: "Push Up - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "three reps in 4.8 s",
    prs: [277],
    date: "2026-09-09",
    exercises: ["Push-Up"],
    notes: "Knee, Incline and Decline Push-Up have their own poses, each from its own clip.",
  },

  // --- Batch 4: arms and shoulders --------------------------------------
  curl: {
    videoId: "-gSM-kqNlUw",
    title: "EZ Bar Curl - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "three reps in 10 s",
    prs: [278],
    date: "2026-09-09",
    exercises: ["Barbell Curl"],
  },
  tricepsExtension: {
    videoId: "y6EdXBdL75A",
    title: "Rope Cable Tricep Pushdown - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "five reps in 11.6 s",
    prs: [279],
    date: "2026-09-09",
    exercises: ["Triceps Pushdown"],
    notes: "Overhead Triceps Extension borrows this pushdown; it needs its own overhead pose.",
  },
  lateralRaise: {
    videoId: "8aUc9snLOxU",
    title: "Dumbbell Lateral Raise - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "front",
    span: "five reps in 9 s",
    prs: [280],
    date: "2026-09-09",
    exercises: ["Dumbbell Lateral Raise"],
  },
  skullCrusher: {
    videoId: "eluOhtYkm-0",
    title: "EZ Bar Skull Crusher - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "head-end",
    span: "three reps in 9 s",
    prs: [281],
    date: "2026-09-09",
    exercises: ["Skull Crusher"],
  },
  dip: {
    videoId: "VNa0hX_y6Fk",
    title: "Weighted Dip - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "three-quarter",
    span: "four reps in 11 s",
    prs: [282],
    date: "2026-09-09",
    exercises: ["Bar Dip"],
  },
  fly: {
    videoId: "AVIBmE5iQrQ",
    title: "Dumbbell Neutral Grip Fly - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "head-end",
    span: "three reps in 11.5 s",
    prs: [283],
    date: "2026-09-09",
    exercises: ["Dumbbell Fly"],
  },

  // --- Batch 5: core and carries ----------------------------------------
  plank: {
    videoId: "rfPf3HCg2Ac",
    title: "Front Plank to Forearm Plank",
    channel: "OPEX Fitness",
    view: "side",
    span: "the forearm phases at 2.5-3, 6-6.5 and 9.5-10 s",
    prs: [284],
    date: "2026-09-09",
    exercises: ["Plank"],
  },
  sidePlank: {
    videoId: "tbWPBOgju9g",
    title: "Side Plank - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "front",
    span: "a 9 s hold",
    prs: [285],
    date: "2026-09-09",
    exercises: ["Side Plank"],
    notes: "Copenhagen Plank (feet on a bench) borrows this floor side plank.",
  },
  // --- Batch 6: the borrowed exercises get their own poses ----------------
  copenhagenPlank: {
    videoId: "tKb76R21AfM",
    title: "Copenhagen Plank",
    channel: "OPEX Fitness",
    view: "front",
    span: "a 7 s hold",
    prs: [293],
    date: "2026-09-10",
    exercises: ["Copenhagen Plank"],
  },
  pallofPress: {
    videoId: "syYBcVbEAFk",
    title: "Cable Standing Pallof Press",
    channel: "OPEX Fitness",
    view: "three-quarter",
    span: "three reps in 10 s",
    prs: [294],
    date: "2026-09-10",
    exercises: ["Pallof Press"],
  },
  overheadCarry: {
    videoId: "dwGP7RAYtxY",
    title: "Dual Kettlebell Overhead Carry - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "front",
    span: "2.5 s of walking toward the camera",
    prs: [295],
    date: "2026-09-10",
    exercises: ["Overhead Carry"],
    notes: "The arms only; the stride is the farmer's carry's, from its side-view clip.",
  },
  frontRackCarry: {
    videoId: "0OzaglIheOc",
    title: "Front Rack Kettlebell Carry - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "front",
    span: "3.5 s of walking toward the camera",
    prs: [295],
    date: "2026-09-10",
    exercises: ["Front Rack Carry"],
    notes: "The arms only; the stride is the farmer's carry's.",
  },
  suitcaseCarry: {
    videoId: "28BIZccT5fs",
    title: "Single Arm Farmers Carry - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "front",
    span: "5 s of walking toward the camera",
    prs: [295],
    date: "2026-09-10",
    exercises: ["Suitcase Carry"],
    notes: "The arms only; the stride is the farmer's carry's.",
  },

  stepUp: {
    videoId: "RRuWVDefORg",
    title: "Step Up - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "three-quarter",
    span: "four step-ups in 19 s",
    prs: [296],
    date: "2026-09-10",
    exercises: ["Step-Up"],
    notes: "Dumbbell Step-Up shares the pose with the bells drawn in the hands.",
  },

  overheadTricepsExtension: {
    videoId: "7h3lG2WnLXg",
    title: "Single Dumbbell Overhead Tricep Extension - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "three reps in 8 s",
    prs: [297],
    date: "2026-09-10",
    exercises: ["Overhead Triceps Extension"],
  },

  boxJump: {
    videoId: "W5QzqIbEWvk",
    title: "Box Jump Step Down - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "three jumps in 10 s",
    prs: [299],
    date: "2026-09-10",
    exercises: ["Box Jump"],
    notes: "Up by a jump, down by a step: the first looping movement.",
  },

  broadJump: {
    videoId: "YjFr2OEivz0",
    title: "Broad Jump | Strength & Conditioning Exercise Library",
    channel: "Flow High Performance",
    view: "side",
    span: "one jump in 6 s",
    prs: [300],
    date: "2026-09-10",
    exercises: ["Broad Jump"],
    notes: "One rep, so the tempo is a single sample. The loop glides back to the start.",
  },

  jumpingLunge: {
    videoId: "BR1A8T9SjIU",
    title: "Jump Lunge - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "eight switches in 9 s",
    prs: [301],
    date: "2026-09-10",
    exercises: ["Jumping Lunge"],
  },

  skaterBound: {
    videoId: "Xqzq9w42-z4",
    title: "Skater Jumps",
    channel: "Exercise Library",
    view: "front",
    span: "nine bounds in 12 s",
    prs: [302],
    date: "2026-09-10",
    exercises: ["Skater Bound"],
    notes: "Frontal keypoints read directly (hip travel, lean, free-foot height), not the lab's sagittal table.",
  },

  kettlebellSnatch: {
    videoId: "y12D2GApeO0",
    title: "Kettlebell Snatch",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reps in 9 s",
    prs: [303],
    date: "2026-09-10",
    exercises: ["Kettlebell Snatch"],
    notes: "The way down is the pull reversed; the clip drops the bell a little further out in front.",
  },

  bearCrawl: {
    videoId: "w089AXf1f_g",
    title: "Crawl - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "ten hand-steps in 9 s",
    prs: [304],
    date: "2026-09-10",
    exercises: ["Bear Crawl"],
    notes: "Raw keypoints (the lab's table drops a crawling figure's legs). Ours crawls on the spot.",
  },

  highKnees: {
    videoId: "cUmfCd-Hznk",
    title: "High Knees | Movement Demo",
    channel: "CrossFit",
    view: "three-quarter",
    span: "nine seconds on the spot",
    prs: [305],
    date: "2026-09-11",
    exercises: ["High Knees"],
    notes: "Near-side view: the angles are projections, +-5.",
  },

  tuckJump: {
    videoId: "w0cI_zLXJFo",
    title: "Tuck Jump",
    channel: "OPEX Bristol - The Future of Personal Training",
    view: "side",
    span: "three jumps in 8.5 s",
    prs: [306],
    date: "2026-09-11",
    exercises: ["Tuck Jump"],
    notes: "Read as raw keypoints (heights, knee under hip). The video sits behind YouTube's consent page.",
  },

  powerClean: {
    videoId: "YEXjyc22Jek",
    title: "Power Clean (side view)",
    channel: "Fitness Pain Free",
    view: "side",
    span: "two reps in 14 s",
    prs: [307],
    date: "2026-09-11",
    exercises: ["Power Clean"],
    notes: "Hang Clean and Kettlebell Clean still borrow the old `clean`.",
  },

  kettlebellClean: {
    videoId: "JrNe81MYEuI",
    title: "Single Arm Kettlebell Clean From Floor",
    channel: "Functional Bodybuilding",
    view: "side",
    span: "six reps in 9 s",
    prs: [308],
    date: "2026-09-11",
    exercises: ["Kettlebell Clean"],
    notes: "Near-side view; the swing-through key keeps the bell out of the thighs, as the snatch's.",
  },

  pushPress: {
    videoId: "xcCYH-UcoZ0",
    title: "Push press (side view)",
    channel: "Armory HPFT",
    view: "side",
    span: "three reps in 11.6 s",
    prs: [309],
    date: "2026-09-11",
    exercises: ["Push Press"],
    notes: "Push Jerk still borrows the strict press; it drops under the bar, which this one does not.",
  },

  pushJerk: {
    videoId: "dboDOX7xY_Q",
    title: "Push Jerk (Side view)",
    channel: "Fitness Pain Free",
    view: "side",
    span: "three reps in 10 s",
    prs: [310],
    date: "2026-09-11",
    exercises: ["Push Jerk"],
    notes: "The second dip -- dropping under a locked-out bar -- is what separates it from the push press.",
  },

  jumpSquat: {
    videoId: "3jJt5gCMRNQ",
    title: "Jump Squats",
    channel: "OPEX Abbotsford",
    view: "three-quarter",
    span: "ten reps in 13 s",
    prs: [311],
    date: "2026-09-11",
    exercises: ["Jump Squat"],
    notes: "Near-side view: the angles are projections, +-5. The arms reach forward at the bottom as a counterbalance.",
  },

  depthJump: {
    videoId: "GeN0S3XCZnM",
    title: "Depth Jump | Olympic Weightlifting Exercise Library",
    channel: "Catalyst Athletics",
    view: "side",
    span: "two reps out of a 1:20 tutorial",
    prs: [312],
    date: "2026-09-11",
    exercises: ["Depth Jump"],
    notes: "A step off the box, not a jump down; the contact before the rebound is 0.2-0.4 s.",
  },

  arnoldPress: {
    videoId: "hHmFzFaSn7U",
    title: "Standing Arnold Dumbbell Press - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "front",
    span: "four reps in 14 s",
    prs: [314],
    date: "2026-09-11",
    exercises: ["Arnold Press"],
    notes: "Front view: the hand path is the lift. The mannequin has no forearm twist, so the palm rotation is not drawn.",
  },

  pecDeck: {
    videoId: "X3Nj2ZPwW04",
    title: "Chest Fly Machine",
    channel: "OPEX Fitness",
    view: "three-quarter",
    span: "three reps in 14 s",
    prs: [298],
    date: "2026-09-10",
    exercises: ["Pec Deck"],
    notes: "The machine's arms are not drawn; the seat is.",
  },

  hangingRaise: {
    videoId: "w0IDQ_05X34",
    title: "Hanging Leg Raises",
    channel: "OPEX San Juan",
    view: "three-quarter",
    span: "four reps in 12 s",
    prs: [286],
    date: "2026-09-09",
    exercises: ["Hanging Leg Raise"],
    notes: "The clip's knees bend (a knee raise); the leg raise keeps its hang, trunk lean and tempo with the knees held straight and the thighs stopping level.",
  },
  hangingKneeRaise: {
    videoId: "w0IDQ_05X34",
    title: "Hanging Leg Raises",
    channel: "OPEX San Juan",
    view: "three-quarter",
    span: "four reps in 12 s",
    prs: [286],
    date: "2026-09-09",
    exercises: ["Hanging Knee Raise"],
    notes: "The clip as measured: knees to the chest.",
  },
  woodchop: {
    videoId: "KnbgKcvOG_c",
    title: "High to Low Cable Oblique Rotation",
    channel: "OPEX Fitness",
    view: "three-quarter",
    span: "three reps in 11 s",
    prs: [287],
    date: "2026-09-09",
    exercises: ["Cable Woodchopper"],
    notes: "Pallof Press (a straight-out press against the cable) borrows this chop.",
  },
  carry: {
    videoId: "K4R8uc1x_OA",
    title: "Dumbbell Farmer's Carry",
    channel: "OPEX Fitness",
    view: "side",
    span: "2.6 s of walking in frame",
    prs: [288],
    date: "2026-09-09",
    exercises: ["Farmer's Carry"],
    notes: "Suitcase, Front Rack and Overhead Carry walk the same way; their loads differ and are not drawn differently yet.",
  },
  russianTwist: {
    videoId: "Hvtxbidjins",
    title: "Russian Twist",
    channel: "OPEX Fitness",
    view: "side",
    span: "six twists in 9.5 s",
    prs: [289],
    date: "2026-09-10",
    exercises: ["Russian Twist"],
  },
  deadBug: {
    videoId: "-VykQ1HD0Vw",
    title: "Alternating Dead Bug",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reaches in 17 s",
    prs: [290],
    date: "2026-09-10",
    exercises: ["Dead Bug"],
  },
  hollowHold: {
    videoId: "EsnM8eBtazU",
    title: "Hollow Body Hold - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "1.25 s into the hold, 3.5 s holding it",
    prs: [291],
    date: "2026-09-10",
    exercises: ["Hollow Hold"],
    notes: "V-Up borrows this hold.",
  },

  // --- Batch 8 correction: the push-up variants -------------------------
  inclinePushUp: {
    videoId: "E--Ls5QtFqI",
    title: "Incline Push Up on Bench - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reps in 12 s",
    prs: [315],
    date: "2026-09-11",
    exercises: ["Incline Push-Up"],
  },

  declinePushUp: {
    videoId: "cnsPwJ2f2B4",
    title: "Decline Push Up - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reps in 11 s",
    prs: [315],
    date: "2026-09-11",
    exercises: ["Decline Push-Up"],
    notes: "On a bench the arm is about as long as the bench is tall, so the lockout is level rather than head-down.",
  },

  // --- Batch 9: the highest-reach poses never authored from a clip --------
  // --- Batch 11: the leftovers, picked by measured defect -----------------
  singleLegHinge: {
    videoId: "pJewPISyHjw",
    title: "Dumbbell Single Leg Romanian Deadlift",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reps in 14.8 s",
    prs: [337],
    date: "2026-09-12",
    exercises: ["Single-Leg Romanian Deadlift", "Single-Leg Deadlift"],
    notes:
      "Read as fractions of the standing hip height. The hip travels 28% of it BACK -- from 11% in front of the standing ankle to 17% behind -- while the shoulder goes the other way; ours walked the pelvis 20% FORWARD. The standing knee holds 173 to 153, twenty degrees, against our fifty four. The trunk reaches 104 off vertical and the hip gives up only 3% of its height. The FREE LEG is taken by angle, not position: its ankle projects 0.370 of the frame from the hip where a straight leg of hers is 0.481, so it swings a fifth of its length out of the film plane -- but the clip does settle that it hangs plumb at the top, reaches 57 degrees behind plumb at the halfway point, and finishes level with the hip, knee near straight at 158.",
  },

  inclineCurl: {
    videoId: "aG7CXiKxepw",
    title: "Incline Dumbbell Curl",
    channel: "OPEX Fitness",
    view: "side",
    span: "three reps in 11.2 s",
    prs: [336],
    date: "2026-09-12",
    exercises: ["Incline Dumbbell Curl"],
    notes:
      "Square side view -- the projected trunk holds 0.249 to 0.288 of the frame throughout. The elbow runs 178 straight down to 26 at the top, the same to within 4 degrees across three reps; ours stopped at 87. The upper arm does not quite hold still either: it drifts 23 degrees further behind the torso as the curl closes, 183 to 206. And the trunk measures 41.5 degrees off vertical, mean over 33 frames, against our 54 -- unlike the incline PRESS, whose lifter arches and whose trunk therefore reads 19 degrees more upright than his own pad, nobody arches on a curl, so here the trunk IS the pad.",
  },

  inclinePress: {
    videoId: "PZ7waXzAzZc",
    title: "Incline Barbell Bench Press",
    channel: "OPEX Fitness",
    view: "side",
    span: "three reps in 6 s",
    prs: [335],
    date: "2026-09-12",
    exercises: ["Incline Barbell Bench Press", "Incline Dumbbell Press"],
    notes:
      "Square side view -- the projected trunk holds 0.123 to 0.158 of the frame throughout, so the sagittal angles are usable. Shoulder-to-wrist over a straight arm runs 98% at lockout to 50% at the chest, the same to within 2% across three reps, elbow 157 to 48. What it CANNOT give is the trunk: his hip-to-shoulder line sits 31 degrees off vertical while the pad is nearer 50, the difference being his arch, and our trunk is a rigid segment lying on the pad. So the arm angles are taken RELATIVE TO THE TRUNK -- 58 degrees off it at lockout, 121 at the chest -- and re-projected onto ours.",
  },

  reverseFly: {
    videoId: "qDnwFycUW0I",
    title: "Cable Reverse Fly",
    channel: "OPEX Fitness",
    view: "back",
    span: "three reps in 10.5 s",
    prs: [334],
    date: "2026-09-12",
    exercises: ["Dumbbell Reverse Fly"],
    notes:
      "A SUBSTITUTION, and the reason is the camera. The two dumbbell clips in the OPEX library (o8x-WppEits, 3cKWQo6tCg0) were measured first and set aside: both are filmed near side on, shoulders only 23 and 30 px apart in frame, so the lateral spread -- the one thing this movement is -- lies along the camera axis and cannot be told apart from one arm forward and one arm back. This one is filmed from BEHIND and settles it: the wrists run 1.0 shoulder widths, hanging straight under the shoulders, to 3.8 wide open, the same to within 0.07 across three reps, with the wrist within 0.005 of shoulder height at every top and the elbow held at 143 to 158, mean 151. It is the STANDING cable version, so it settles nothing about the trunk -- ours stays hinged at 92 -- but the joint doing the work, horizontal abduction of the shoulder, is the same lift.",
  },

  seatedCalfRaise: {
    videoId: "2Q-HQ3mnePg",
    title: "Seated Calf Raise Machine",
    channel: "OPEX Fitness",
    view: "side",
    span: "five reps in 8.4 s",
    prs: [333],
    date: "2026-09-12",
    exercises: ["Seated Calf Raise"],
    notes:
      "What it settles beyond argument: the machine puts the ball of the foot on a RAISED PLATE and the heel drops below plate level, which is where the calf is stretched -- ours had the foot flat on the floor, so that half of the range did not exist. It also holds the knee at 83 to 89 degrees in all 37 frames, mean 86. What it CANNOT settle is any travel distance: its hip keypoint rises 8 cm over a rep, which a seated hip on a fixed seat cannot do, so the whole skeleton estimate drifts in phase with the lift and its scale is untrustworthy here. The heel range is therefore authored from the plate geometry and capped by keeping the knee inside the clip's own band at the start.",
  },

  curtsyLunge: {
    videoId: "7ptRZXL5MBs",
    title: "Goblet Curtsy Squat",
    channel: "OPEX Fitness",
    view: "front",
    span: "three reps in 10.8 s",
    prs: [332],
    date: "2026-09-12",
    exercises: ["Curtsy Lunge"],
    notes:
      "Read as RATIOS of the standing hip height, because his proportions are not the model's -- his thigh is 0.58 of his hip height and ours 0.50. The hip drops 47% of that height (ours 30%); the TRAILING KNEE arrives at the floor, level with the standing ankle, where ours stopped 22% up; the trailing heel lifts to 14% with the knee BELOW it; the trailing foot finishes 1.5 shoulder widths past the standing foot from a stance of 0.72; and the trunk leaves vertical by 15 degrees AWAY from the crossing leg. A front camera cannot read a knee angle in this movement -- the standing shin travels forward, out of the film plane -- so no knee angle is quoted.",
  },

  // --- Batch 10: the cable family ----------------------------------------
  cableKickback: {
    videoId: "iElJ4Ngx--k",
    title: "Cable Glute Kickback",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reps in 12.3 s",
    prs: [331],
    date: "2026-09-12",
    exercises: ["Cable Kickback"],
    notes: "Close to square -- the projected trunk holds 0.234 to 0.264 of the frame throughout -- so the sagittal angles are usable. The working KNEE NEVER STRAIGHTENS: 134 at the bottom, 119 at full extension, and the largest reading anywhere in the clip is 151 on a single frame. The trunk is hinged over a bench at 46 degrees at every top position in all four reps. The hands are still, moving 0.014 of the frame horizontally across a whole rep, and sit only 0.085 in front of the pelvis.",
  },

  cableCrunch: {
    videoId: "2ndlUfl5JPo",
    title: "Kneeling Cable Crunch",
    channel: "OPEX Fitness",
    view: "three-quarter",
    span: "three reps in 9.6 s",
    prs: [330],
    date: "2026-09-11",
    exercises: ["Cable Crunch"],
    notes: "Not square to the lifter -- the projected trunk runs 0.23 to 0.33 of the frame as she turns through the rep -- so the angles are read the projection-proof way, from the VERTICAL drop of the shoulder below the hip over a trunk of 0.330. On those terms the hip-to-shoulder line sweeps 33 to 121 degrees off vertical, the same to within 3 degrees in all three reps, and at the bottom her NOSE IS BELOW HER KNEE. Her hips also rise off the heels as she curls, 0.255 to 0.279 above the knee. Our trunk is one rigid segment and hers rounds, so the pose matches the line her hip and shoulder make, not the shape of her spine.",
  },

  cablePullThrough: {
    videoId: "A30YKvpWGu4",
    title: "Cable Pull Through",
    channel: "OPEX Fitness",
    view: "three-quarter",
    span: "four reps in 12.6 s",
    prs: [329],
    date: "2026-09-11",
    exercises: ["Cable Pull-Through"],
    notes: "NOT square to the lifter: the trunk projects 0.268 of the frame standing and 0.181 at the bottom, and a rigid trunk cannot lose a third of its length to a square side camera. So no horizontal distance from this clip is quotable. What it does settle is anything measured in HEIGHT -- the hip stays level (0.432 to 0.430 above the ankle), the trunk reaches 104 from vertical, the arm swings from 9 degrees forward of straight down to 66 behind it -- plus the DIRECTION of hip and shoulder travel, which no projection reverses, plus the tempo.",
  },

  straightArmPulldown: {
    videoId: "nAkTIeJ_Aus",
    title: "Standing Cable Straight Arm Pulldown",
    channel: "OPEX Fitness",
    view: "side",
    span: "three reps in 11.2 s",
    prs: [328],
    date: "2026-09-11",
    exercises: ["Straight-Arm Pulldown"],
    notes: "The shoulder-to-wrist line -- the line a locked arm makes -- reads 64 from vertical at the start and 167 at the finish, in all three reps within 5 degrees; ours started at 41, almost straight overhead. The clip CANNOT settle the elbow at the top: this lifter stands close enough that the bar reaches his forehead and his elbow folds to about 135 there, which is the clip rather than the lift, so the hand path is taken and the arm is kept locked.",
  },

  facePull: {
    videoId: "5ZC4LagfDQ4",
    title: "Cable Rope Face Pull",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reps in 11.6 s",
    prs: [327],
    date: "2026-09-11",
    exercises: ["Face Pull"],
    notes: "Both hands finish beside the head and MoveNet tangles the near and far arm there, so the elbow angles are unusable and are not quoted. What the frames show plainly is the pulley height -- well above the head -- and that the elbows stay high.",
  },

  cableCurl: {
    videoId: "h9DPY5pCaGA",
    title: "Cable Curl",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reps in 12.1 s",
    prs: [326],
    date: "2026-09-11",
    exercises: ["Cable Curl"],
    notes: "Elbow 160 hanging to 24-31 at the top, upper arm staying at the side. Ours stopped at 102 and its first two keys were 160 and 158, so the opening third of the animation did not move.",
  },

  cableLateralRaise: {
    videoId: "dQPTeeqgJqA",
    title: "Cable Lateral Raise",
    channel: "OPEX Fitness",
    view: "front",
    span: "four reps in 12.1 s",
    prs: [325],
    date: "2026-09-11",
    exercises: ["Cable Lateral Raise"],
    notes: "Low pulleys, which the pose already had. What it corrected was the finish: the clip takes the hand ABOVE the shoulder, ours stopped 5 cm below it.",
  },

  cableFly: {
    videoId: "jtkaC-mq1Xk",
    title: "Cable Fly - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "front",
    span: "four reps in 12.4 s",
    prs: [324],
    date: "2026-09-11",
    exercises: ["Cable Chest Fly"],
    notes: "A front camera cannot see an arm reaching forward, so the elbow angle in this clip is a projection and is not used; what it settles is the HAND PATH -- one height, wide to together -- and the pulley height.",
  },

  lateralLunge: {
    videoId: "rSaWYv37zzE",
    title: "Goblet Cossack Squat - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "front",
    span: "four reps in 15.7 s",
    prs: [323],
    date: "2026-09-11",
    exercises: ["Cossack Squat"],
    notes: "Lateral Lunge shares this pose and STEPS OUT from a narrow stance; the clip holds one wide stance throughout and shifts side to side, which is the cossack. What transferred is the depth, the dead-straight trailing leg, the hands and the tempo.",
  },

  proneRaise: {
    videoId: "W8vlZfmxOpM",
    title: "Superman Hold - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "a 7 s hold",
    prs: [322],
    date: "2026-09-11",
    exercises: ["Superman"],
    notes: "A hold, so it gives one position and no tempo. It confirmed the trunk and legs (ankle lift 19.2 cm against the clip's 19.3) and corrected the arms, which finished 15.6 cm above the head. Prone Y-T-W Raise and Reverse Snow Angel share this pose and both lift the arms, so the top is a compromise between the three.",
  },

  invertedRow: {
    videoId: "B90sF7dbP04",
    title: "Ring Row",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reps in 10.8 s",
    prs: [321],
    date: "2026-09-11",
    exercises: ["Inverted Row"],
    notes: "Towel Row and Doorway Row borrow this pose. The clip is on rings; the pose draws a fixed bar, which is why the top stops at the shallow end of the clip's elbow band -- on rings the head passes between them, under a bar it does not.",
  },

  calfRaise: {
    videoId: "LnWEIjIls-M",
    title: "Standing Calf Raise",
    channel: "OPEX Fitness",
    view: "back",
    span: "four reps in 11.6 s",
    prs: [320],
    date: "2026-09-11",
    exercises: ["Bodyweight Calf Raise", "Dumbbell Calf Raise"],
    notes: "Filmed from behind and done on a LEDGE with the heels dropping below the step, so it settles the tempo and nothing about the angles; the pose draws the floor version the library cue describes and its range was left alone. Single-Leg Calf Raise borrows this pose.",
  },

  legCurl: {
    videoId: "xKOyGU0AfOE",
    title: "Prone Hamstring Curl Machine",
    channel: "OPEX Fitness",
    view: "side",
    span: "four reps in 12.4 s",
    prs: [319],
    date: "2026-09-11",
    exercises: ["Lying Leg Curl", "Seated Leg Curl"],
    notes: "MoveNet scores only 0.26-0.71 on this one (small figure, gym clutter, the two legs confused when curled), so the range was read from the clusters the whole clip agrees on rather than per-frame angles. Nordic Hamstring Curl is ALSO mapped to this pose and should not be: it is a kneeling bodyweight movement with no machine.",
  },

  lunge: {
    videoId: "Q2k3kYbtOcI",
    title: "Dumbbell Reverse Lunge",
    channel: "OPEX Fitness",
    view: "side",
    span: "three reps in 11.7 s",
    prs: [318],
    date: "2026-09-11",
    exercises: ["Bodyweight Reverse Lunge", "Dumbbell Lunge"],
    notes: "Barbell Walking Lunge borrows this pose; the split stance is held throughout rather than stepped, which is the library convention for the lunge family.",
  },

  gobletSquat: {
    videoId: "pEGfGwp6IEA",
    title: "Goblet Squat - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "three-quarter",
    span: "three reps in 11.2 s",
    prs: [317],
    date: "2026-09-11",
    exercises: ["Goblet Squat"],
    notes: "Confirms the shared squat frames (parallel bottom, same hip drop) rather than correcting them; a three-quarter camera cannot settle the trunk angle. What it settled was the tempo and the fact that the bell stays ON the chest.",
  },

  hinge: {
    videoId: "TN3DHmd1Fe8",
    title: "Conventional Deadlift - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "three reps in 13.8 s",
    prs: [316],
    date: "2026-09-11",
    exercises: ["Conventional Deadlift"],
    notes: "Rack Pull, Back Extension and Hip Hinge Wall Touch borrow this hinge; the clip lowers the bar to just off the floor rather than setting it down.",
  },

  kneePushUp: {
    videoId: "8XQ-okb5NWE",
    title: "Knee Push Up - OPEX Exercise Library",
    channel: "OPEX Fitness",
    view: "side",
    span: "six reps in 11 s",
    prs: [315],
    date: "2026-09-11",
    exercises: ["Knee Push-Up"],
  },
};

export function referenceClipUrl(clip: ReferenceClip): string {
  return `https://www.youtube.com/watch?v=${clip.videoId}`;
}
